#! /usr/bin/env bash

set -e

# don't use spaces
SIFTGPU_LIBPATH="../SiftGPU/bin"

[ ! -d $SIFTGPU_LIBPATH ] \
        && echo "Error: specify dir to libsiftgpu.so" \
        && exit 1

if [ -z $LD_LIBRARY_PATH ]; then
    LD_LIBRARY_PATH=$SIFTGPU_LIBPATH
else
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SIFTGPU_LIBPATH
fi
export LD_LIBRARY_PATH

if [ 0 -eq $# ]; then
    ./app -help
else
    ./app $@
fi

