#! /usr/bin/env python

import os

cc = os.environ.get('CC', 'gcc-4.7')
cxx = os.environ.get('CXX', 'g++-4.7')

cuda_root = os.environ.get('CUDA_ROOT', '/usr/local/cuda')

ccflags = ['-Wall', '-Wextra', '-Werror']
ccflags.append('-Wno-unused-function')
ccflags.append('-Wno-unused-parameter')
ccflags.append('-Wno-unused-variable')
ccflags.append('-std=c++11')

cpath = ['/usr/local/include']

libpath = []

libs = ['opencv_core', 'opencv_gpu', 'opencv_stitching', 'gomp']

if ARGUMENTS.get('debug', 0):
    ccflags.extend(['-ggdb', '-O0'])
else:
    ccflags.append('-O3')

env = Environment(CC = cc, CXX = cxx)
env.Append(CCFLAGS = ccflags)
env.Append(CPPPATH = cpath)
env.Append(LIBPATH = libpath)
env.Append(LIBS = libs)

sources = ['io.cpp', 'stitcher.cpp', 'matchers.cpp', 'motion_estimators.cpp']

env.Program('stitcher', ['main.cpp', sources])

